#!/bin/bash
target="$1" ; shift
spec="$1"

if [ -z "$target" ] ; then
    echo "usage: wct-project.sh /path/to/target [<spec>]"
    exit 1
fi

spack=/srv/spack/local/bin/spack
if [ ! -x $spack ] ; then
    echo "No spack found"
    exit 1
fi

tdir="$(realpath "$target")"

if [ -f "$tdir/.envrc" ] ; then
    echo "Project area exits: $tdir"
    exit 1
fi

if [ -z "$spec" ] ; then
    spec=$( $spack find -l -v wire-cell-toolkit|tail -1 | awk '{print $1}' )
    if [ "$spec" = "==>" ] ; then
        echo "Failed to find WCT in spack, try:"
        echo "  spack install wire-cell-toolkit"
        echo "See https://github.com/wirecell/wire-cell-spack"
        exit 1
    fi
    spec="/$spec"
    echo "Found spec: $spec"
fi

mkdir -p "$tdir"
cd "$tdir"

$spack view add -i local "$spec"

if [ -d python ] ; then
    echo "wire-cell-python is already cloned"
else
    git clone git@github.com:wirecell/wire-cell-python.git python
fi
if [ -d toolkit ] ; then
    echo "wire-cell-toolkit is already cloned"
else
    git clone git@github.com:wirecell/wire-cell-toolkit.git toolkit
fi


cat <<EOF > .envrc

load_prefix local
export WIRECELL_PREFIX=\$PWD/local
export WIRECELL_CONFIG="cd \$PWD/toolkit && 
./wcb configure \
   --prefix=\$WIRECELL_PREFIX \
   --with-jsonnet=\$WIRECELL_PREFIX \
   --with-jsonnet-libs=gojsonnet \
   --with-eigen-include=\$WIRECELL_PREFIX/include/eigen3 \
   --boost-mt --boost-libs=\$WIRECELL_PREFIX/lib --boost-include=\$WIRECELL_PREFIX/include &&
cd -"
export WIRECELL_BUILD="cd \$PWD/toolkit && ./wcb install --notests && cd -"
path_add WIRECELL_PATH \$PWD/toolkit/cfg
path_add WIRECELL_PATH /home/bv/opt/wire-cell-data
layout python3
EOF


echo "### next steps, run:"
echo "cd $tdir && direnv allow"
echo "bash -c \"\$WIRECELL_CONFIG\" && bash -c \"\$WIRECELL_BUILD\""
echo "cd python && pip install -e . && cd -"
